### ISSUE TITLE
How to change HANDLES SCALE, CONE RADIUS and other handle settings?

### ISSUE THREAD

**Issue by quacrobat** [tocttou/three-freeform-controls#11]
Hi, my objects are very large (100x100x100), so I need to scale the controls up significantly. 
I can change the radius of the controls using the separation parameter, but the cones and the handlebars remain too small (checking in the code: DEFAULT_CONE_RADIUS = 0.3, should be around 10 for me). 
How can I set the these values at run time?
Thanks for a great library btw :)

**Comment by chaitanya-deep** [comment]
The controls are just three.js objects.
It is possible to set the scale of controls as a whole. Although the lines would still look thin since [three.js lines](https://threejs.org/docs/#api/en/objects/Line) do not have a thickness property, all the handles and planes will scale proportionally.

Something like this should work:
```
const controlsManager = new FreeformControls.ControlsManager(camera, renderer.domElement);
scene.add(controlsManager);
const controls = controlsManager.anchor(box);
controls.scale.set(33, 33, 33);
```
